language: r
cache: packages

r_build_args: --no-build-vignettes
r_check_args: --no-vignettes

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgsl0-dev libegl1-mesa libegl1-mesa-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
  
  
  
  
